mongodb:
    db_name: stfa_db
    username: stfa
    password: S3c1rItyT3st4bl3#
    #host: stfa_db
    host: 127.0.0.1
    port: 27017
    auth_source: admin
jwt:
    secret_key: j4tS3cReT$
    algorithm: HS256